import React from "react";

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};
function Movie() {
  return (
    <>
      <div className="text-primary text-3xl underline">Movie</div>
      <a href="/">Home</a>
    </>
  );
}

export default Movie;
